// Type definitions specifically for Matter.js as used by Phaser 3
//
// Definitions by: Ivane Gegia <https://twitter.com/ivanegegia>,
//                 David Asmuth <https://github.com/piranha771>,
//                 Piotr Pietrzak <https://github.com/hasparus>,
//                 Richard Davey <rich@photonstorm.com>
// DO NOT EDIT THIS FILE! It was generated by running `npm run tsgen`
